Test web app
Elisha-Tetteyfio/Math-Magicians pull request #7
Opened 2022-07-15 17:22 UTC by Elisha-Tetteyfio

In this pull request, I and @BwalyaNonde added tests to the functions and components

2022-07-15 17:42 UTC, Ismailco requested changes
### Hi @Elisha-Tetteyfio, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ All tests working properly 
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-15 17:42 UTC, Ismailco commented on .babelrc
> +
- [ ] Kindly remove any unused commented code, this will make your code cleaner

2022-07-15 17:42 UTC, Ismailco commented on src/tests/snapshot.test.js
> +// import * as styles from '../components/Header.css';
- [ ]  Kindly remove any unused commented code, this will make your code cleaner

2022-07-15 17:42 UTC, Ismailco commented on src/tests/snapshot.test.js
> +import React from 'react';
- [ ] Greate work testing the functions of the app, kindly consider also testing the user interaction by using `React Testing Library`

2022-07-15 17:45 UTC, Ismailco commented
@Elisha-Tetteyfio, Sorry I forgot, this project is supposed to be created using the peer-programming, kindly your partner needs to contribute to this project

2022-07-16 12:41 UTC, OLIPLICHE reviewed
Hi @Elisha-Tetteyfio , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is supposed to be pair programming. As mentioned in the previous review, your partner needs to contribute and we will be checking the committed story about the contribution.  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-16 12:47 UTC, Elisha-Tetteyfio commented
Hello @OLIPLICHE, me and my partner, @BwalyaNonde, worked together on this.
So she corrected all the changes from the previous code review

2022-07-16 12:48 UTC, OLIPLICHE commented
- [ ] Hi, Sorry, I did not pay attention to the new commit messages. The second student has contributed. and congratulation that your project is working fine
- [ ]
![Capture](https://user-images.githubusercontent.com/63972670/179355508-f28156c6-1a6b-470c-a2bb-51abf9efbaf5.PNG)
- Please submit and it will be aproved

2022-07-16 12:50 UTC, Elisha-Tetteyfio commented
Thank you @OLIPLICHE , but it still says `request review` on the dashboard instead of `submit`?
Are we supposed to request another review??

2022-07-16 12:52 UTC, OLIPLICHE commented
Please request for review. submit the same PR.

2022-07-16 12:52 UTC, Elisha-Tetteyfio commented
Ok sure ....Thank you

2022-07-16 12:59 UTC, mahbubul14 approved these changes
# Project Approved :trophy: :tada: 

Hi @Elisha-Tetteyfio & @BwalyaNonde , 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Descriptive readme file.
:heavy_check_mark: Well implemented suggested changes.

### Optional suggestions :arrow_down_small: 

- [ ] kindly add social media links for the both author at author section in the readme file.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-07-16 13:03 UTC, merged